POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "full_name": "Jane Schmoe",
    "email": "j.schmoe@mail.com",
    "password": "1234566",
    "password2": "1234566"
}

####

POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "email": "row@mail.com",
    "password": "123456"
}
