POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "full_name": "Jane Schmoe",
    "email": "j.schmoe@mail.com",
    "password": "1234566",
    "password2": "1234566"
}

####

POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "email": "row@mail.com",
    "password": "123456"
}

####

GET  http://localhost:3000/accounts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiamFuaW5lQG1haWwuY29tIiwiaWF0IjoxNjM1MTc3MzYzLCJleHAiOjE2MzUxODA5NjN9.cU4TI-2Hm2lSUJowBRFjnWJEZMBtgT4MICIHXmhJA7Y

####

POST  http://localhost:3000/accounts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiamFuaW5lQG1haWwuY29tIiwiaWF0IjoxNjM1MTc3MzYzLCJleHAiOjE2MzUxODA5NjN9.cU4TI-2Hm2lSUJowBRFjnWJEZMBtgT4MICIHXmhJA7Y
